## Broadcasting

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(0,10, [2,3])
B = np.ones(A.shape)

In [3]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [4]:
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
A + B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])