In [4]:
import numpy as np

In [25]:
np.random.seed(0)
A = np.random.randint(0,10,[6,6])
A

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3]])

## Methodes ndarray

In [3]:
A.sum(axis=0)

array([ 8,  7, 12])

In [4]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27], dtype=int32)

In [5]:
A.prod()

0

In [6]:
A.min(axis=0)

array([3, 0, 3])

In [7]:
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [8]:
A.argsort()

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [9]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

## Statistiques 

In [10]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [11]:
A.mean()

4.5

In [12]:
A.std()

2.9297326385411577

In [13]:
A.var()

8.583333333333334

In [14]:
np.corrcoef(A)[0,1]

-0.563621480190678

In [26]:
value, counts = np.unique(A, return_counts=True) #return elements and count of each element

In [27]:
counts

array([3, 3, 2, 8, 2, 4, 2, 4, 5, 3], dtype=int64)

In [29]:
value[counts.argsort()]

array([2, 4, 6, 0, 1, 9, 5, 7, 8, 3])

In [30]:
for i, j in zip(value[counts.argsort()], counts[counts.argsort()]):
    print(f'{i} apparait : {j} fois')

2 apparait : 2 fois
4 apparait : 2 fois
6 apparait : 2 fois
0 apparait : 3 fois
1 apparait : 3 fois
9 apparait : 3 fois
5 apparait : 4 fois
7 apparait : 4 fois
8 apparait : 5 fois
3 apparait : 8 fois


## NAN Corrections

In [33]:
A = np.random.randn(5,5)
A[0,2] = np.nan
A[4,4] = np.nan
A

array([[ 0.85292596,  0.01835718,         nan,  0.99627783, -0.49114966],
       [ 0.71267817,  1.11334035, -2.15367459, -0.41611148, -1.07089699],
       [ 0.22113881, -1.12305712, -1.05075796,  1.01207905,  1.54371643],
       [-0.40211489,  0.8647491 , -0.22686923,  0.81116027,  0.28779461],
       [-0.53846816,  1.9084621 , -0.475776  ,  1.44073112,         nan]])

In [34]:
np.nanmean(A)

0.16671890940463974

In [38]:
np.isnan(A)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

In [39]:
np.isnan(A).sum()

2

In [40]:
np.isnan(A).sum()/A.size

0.08

In [41]:
A[np.isnan(A)] = 0

In [42]:
A

array([[ 0.85292596,  0.01835718,  0.        ,  0.99627783, -0.49114966],
       [ 0.71267817,  1.11334035, -2.15367459, -0.41611148, -1.07089699],
       [ 0.22113881, -1.12305712, -1.05075796,  1.01207905,  1.54371643],
       [-0.40211489,  0.8647491 , -0.22686923,  0.81116027,  0.28779461],
       [-0.53846816,  1.9084621 , -0.475776  ,  1.44073112,  0.        ]])

## Algebre linéaire

In [43]:
A = np.ones((2,3))
B = np.ones((3,2))

In [44]:
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [47]:
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [48]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [59]:
A = np.random.randint(0,10,[3,3])

In [60]:
A

array([[2, 8, 6],
       [6, 9, 1],
       [6, 8, 8]])

In [61]:
np.linalg.det(A)

-243.99999999999986

In [62]:
np.linalg.inv(A)

array([[-0.26229508,  0.06557377,  0.18852459],
       [ 0.17213115,  0.08196721, -0.13934426],
       [ 0.02459016, -0.13114754,  0.12295082]])

In [64]:
np.linalg.pinv(A)

array([[-0.26229508,  0.06557377,  0.18852459],
       [ 0.17213115,  0.08196721, -0.13934426],
       [ 0.02459016, -0.13114754,  0.12295082]])

In [65]:
np.linalg.eig(A) #valeur propre et vecteur propre

(array([17.38778554, -3.02568715,  4.63790161]),
 array([[-0.51930736, -0.88711532,  0.24812175],
        [-0.45752716,  0.42830899, -0.52754746],
        [-0.72179551,  0.17198203,  0.8124834 ]]))

## EXERCICE

In [5]:
np.random.seed(0)
A = np.random.randint(0,100,[10,5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [6]:
T = np.ones((A.shape[0],A.shape[1]))
for i in range(A.shape[1]) :
        C = (A[:,i:i+1]-A[:,i:i+1].mean()) / A[:,i:i+1].std()
        T = np.concatenate((T[:,:i],C), axis=1)
        
    
    
T

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

## Solution

In [11]:
D = (A - A.mean(axis=0)) / A.std(axis=0)
D

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])