In [1]:
import numpy as np

In [13]:
np.random.seed(0)
A = np.random.randint(0,10,[2,3])
A

array([[5, 0, 3],
       [3, 7, 9]])

## Methodes ndarray

In [4]:
A.sum(axis=0)

array([ 8,  7, 12])

In [5]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27], dtype=int32)

In [6]:
A.prod()

0

In [8]:
A.min(axis=0)

array([3, 0, 3])

In [10]:
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [15]:
A.argsort()

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [18]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

## Statistiques 

In [19]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [20]:
A.mean()

4.5

In [21]:
A.std()

2.9297326385411577

In [22]:
A.var()

8.583333333333334

In [25]:
np.corrcoef(A)[0,1]

-0.563621480190678