In [1]:
import numpy as np

In [2]:
# Une liste de listes est transformée en un tableau multi-dimensionnel
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
np.random.random((3,3))

array([[0.77070899, 0.48084865, 0.71352609],
       [0.31970195, 0.1976264 , 0.11888877],
       [0.60346258, 0.30604889, 0.39318583]])

In [18]:
np.random.randint(6,10)

8

In [19]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int32


In [20]:
print(x1)

# Pour accéder au premier élément
print(x1[0])

# Pour accéder au dernier élément
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2[0,1])

# On peut aussi modifier les valeurs
x1[1] = "1000"
print(x1)

# Attention au type
x1[1] = 3.14
print(x1)

[5 0 3 3 7 9]
5
9
5
[   5 1000    3    3    7    9]
[5 3 3 3 7 9]


In [21]:
print(x1[:5])  # Les cinq premiers éléments

print(x1[5:])  # Les éléments à partir de l'index 5

print(x1[::2])  # Un élément sur deux

[5 3 3 3 7]
[9]
[5 3 7]


In [22]:
print(x2)

x2[0,:] # La première ligne

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([3, 5, 2, 4])

In [26]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [34]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [35]:
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

tableau_large = np.random.randint(1, 100, size=1000000)

# Ceci est une facilité des notebooks jupyter pour 
# mesurer le temps d'exécution d'une instruction
%timeit calcul_inverse(tableau_large)

[0.11111111 0.5        0.16666667 0.11111111 0.2       ]
5.36 s ± 138 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [36]:
%timeit (1.0 / tableau_large)

10.3 ms ± 959 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
x = np.random.rand(3,3)
x > 0.5

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

In [38]:
x[x>0.5]

array([0.84627748, 0.703217  , 0.84843905, 0.90182436, 0.51108795,
       0.55506003])

In [39]:
np.where(x > 0.5)

(array([0, 0, 1, 1, 1, 2], dtype=int64),
 array([0, 1, 0, 1, 2, 1], dtype=int64))

In [40]:
L = np.random.random(100)
np.sum(L)

49.09899667867994

In [43]:
np.mean(L)

0.4909899667867994

In [42]:
np.std(L)

0.2898644666770316

In [44]:
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

259 ms ± 23.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
675 µs ± 24.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [45]:
M = np.random.random((3, 4))
print(M)
# Notez la syntax variable.fonction au lieu de 
# np.fonction(variable). Les deux sont possibles si
# la variable est un tableau Numpy.
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))

[[0.81001412 0.08782143 0.15618846 0.73099033]
 [0.6427996  0.09425156 0.1035502  0.32354189]
 [0.3706353  0.87966194 0.44429964 0.67253984]]
La somme de tous les éléments de M:  5.316294300734639
Les sommes des colonnes de M:  [1.82344903 1.06173492 0.7040383  1.72707205]


In [48]:
a = np.arange(3)

In [49]:
a

array([0, 1, 2])

In [51]:
b = np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [52]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])