In [1]:
import numpy as np

In [9]:
A = np.array([1,2,3])
print(A.size)
print(A.shape)

3
(3,)


In [12]:
B = np.zeros((3,2))
B.shape

(3, 2)

In [57]:
C = np.ones((5,6))
C.size

30

In [15]:
D = np.full((2,3), 9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [23]:
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.linspace(0,10,20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Manipulation

In [35]:
X = np.ones((3,2))
Y = np.zeros((3,2))

In [36]:
print(X)
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [38]:
Z = np.hstack((X,Y))
Z.shape

(3, 4)

In [39]:
Z = np.vstack((X,Y))
Z.shape

(6, 2)

In [48]:
T = np.concatenate((X,Y), axis=0)
T

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
T = T.reshape((3,4))
T

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [49]:
T.ravel()

array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.])

## Exercice

In [65]:
def initialisation(m,n):
    A = np.random.randn(m, n)
    B = np.ones((m,1))
    C = np.concatenate((A,B), axis=1)
    return C

In [66]:
initialisation(6,2)

array([[ 0.97663904,  0.3563664 ,  1.        ],
       [ 0.70657317,  0.01050002,  1.        ],
       [ 1.78587049,  0.12691209,  1.        ],
       [ 0.40198936,  1.8831507 ,  1.        ],
       [-1.34775906, -1.270485  ,  1.        ],
       [ 0.96939671, -1.17312341,  1.        ]])